version: 1.0.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  parallel: true
  verbosity: minimal
after_build:
- ps: 7z a "LunaMultiPlayer-$env:configuration.zip" "$env:APPVEYOR_BUILD_FOLDER\Artifacts\$env:configuration\Client" "$env:APPVEYOR_BUILD_FOLDER\Artifacts\$env:configuration\Server" "$env:APPVEYOR_BUILD_FOLDER\Artifacts\$env:configuration\MasterServer"
artifacts:
- path: .\LunaMultiPlayer-$(configuration).zip
  name: LunaMultiPlayer.zip
deploy: off